### ISSUE TITLE
ssh container

### ISSUE THREAD

**Issue by senorpasajero** [eugeneware/docker-wordpress-nginx#16]
Hi, is it possible create a ssh connection with the docker container? I need edit wp-config file.

**Comment by valentt** [comment]
Just use docker-enter instead of ssh, just gogole for it.

**Comment by eugeneware** [comment]
Agreed. Use docker exec. Including ssh is a docker anti-pattern for these kinds of situations.

**Comment by strarsis** [comment]
How to use [wp cli](http://wp-cli.org/) without SSH, just with Docker exec?
