### ISSUE TITLE
You should lock down the version of FROM=ubuntu

### ISSUE THREAD

**Issue by AsavarTzeth** [eugeneware/docker-wordpress-nginx#22]
I have noticed that because you have not specified the version of the ubuntu base image you use, docker pulls all versions available. This takes more time than necessary and makes a mess in your image repository.

If I understand things correctly you have now moved to 14.04 (nice!). Thus you should change "FROM=ubuntu" to "FROM=ubuntu:14.04".

Yes I know I can change this myself before building, but since other versions than the intended one often fail to build there is no point in not locking it to your recommended version.

Thanks in advance, and thanks for the recent quick fix.

**Comment by valentt** [comment]
If this issue is fixed please close this issue.

**Comment by AsavarTzeth** [comment]
I had completely forgotten about this. Thank you for reminding me!
