### ISSUE TITLE
How do I attach a volume so that I can edit the files with sublime

### ISSUE THREAD

**Issue by hsingh23** [eugeneware/docker-wordpress-nginx#37]
How do I attach a volume so that I can edit the files with sublime text?

I tried docker run -v local_absolute_path:/usr/share/nginx/www/ -d -p 8000:80 --name=wp eugeneware/docker-wordpress-nginx

**Comment by adiazpy** [comment]
I think it's better via terminal with docker exec -it <container-id> bash

**Comment by scalopus** [comment]
@hsingh23 / @enejb #40 , have you found solution yet? I also looking for it.

I try with 
`sudo docker run -v /usr/share/nginx:/usr/share/nginx -p 80:80 --name docker-wordpress-nginx -d eugeneware/docker-wordpress-nginx` but it still not work with what I expected.

**Comment by oroce** [comment]
oh you can do that pretty easily: 

```
cd this-is-my-very-theme
docker run -v $(pwd):/usr/share/nginx/www/wp-content/themes/my-very-theme -p 80:80 -d eugeneware/docker-wordpress-nginx`
```

Go to Appearance -> Themes: `my-very-theme` will be there.

**Comment by hsingh23** [comment]
Thanks
